language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "sgrillon14-github"

jdk:
- oraclejdk8

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sgrillon14-github -Dsonar.login=$SONAR_TOKEN -Punit-tests

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
